name: Link Checker for Pull requests
on: pull_request
jobs:
  fileChanges:
    runs-on: ubuntu-latest
    outputs:
      diff-files: ${{ steps.git-diff-action.outputs.json-diff.files }}
    steps:
      - uses: actions/checkout@v4
      - uses: GrantBirki/git-diff-action@v2.7.0
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          file_output_only: "true"

  linkChecker:
    runs-on: ubuntu-latest
    needs: fileChanges
    strategy:
      matrix:
        file: ${{ fromJSON(needs.fileChanges.outputs.diff-files) }}
    steps:
      - name: download Lychee
        run: |
           wget https://github.com/lycheeverse/lychee/releases/download/nightly/lychee-x86_64-unknown-linux-gnu.tar.gz
           tar xzf lychee-x86_64-unknown-linux-gnu.tar.gz

      - name: Check all this PR's additions for broken links
        run: |
          export LATEST_BASE_COMMIT=$(git rev-parse ${{ github.sha }}^)
          echo "latest base commit: ${LATEST_BASE_COMMIT}"
          echo "checking ${{ matrix.file.path }} for added broken links..."
          git diff -U0 ${LATEST_BASE_COMMIT} ${{ github.event.pull_request.head.sha }} -- ${{ matrix.file.path }} | grep -v "+++" | grep "^+" | cut -c 2- | ./lychee -
