name: Link Checker for Pull requests
on: pull_request
jobs:
  changedFiles:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      base_sha: ${{ steps.get-base-sha.outputs.base_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v45
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.md
          matrix: true
      - name: get base SHA
        id: get-base-sha
        run: echo 'base_sha=$(git rev-parse ${{ github.sha }}^)' >> $GITHUB_OUTPUT

  installLychee:
    runs-on: ubuntu-latest
    needs: changedFiles
    steps:
      - name: download Lychee
        run: |
          wget https://github.com/lycheeverse/lychee/releases/download/nightly/lychee-x86_64-unknown-linux-gnu.tar.gz
          tar xzf lychee-x86_64-unknown-linux-gnu.tar.gz

      - name: archive lychee
        uses: actions/upload-artifact@v4
        with:
          name: lychee-executable
          path: lychee
  
  linkChecker:
    runs-on: ubuntu-latest
    needs: [changedFiles, installLychee]
    strategy:
      matrix:
        file: ${{ fromJSON(needs.changedFiles.outputs.files) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: download lychee from archive
        uses: actions/download-artifact@v4
        with:
          name: lychee-executable
      - name: set lychee permissions because artifact permissions get reset
        run: chmod +x lychee
      - name: Check all this PR's additions for broken links
        run: |
          echo "checking ${{ matrix.file }} for added broken links..."
          git diff -U0 ${{ needs.changedFiles.outputs.base_sha }} ${{ github.event.pull_request.head.sha }} -- ${{ matrix.file }} | grep -v "+++" | grep "^+" | cut -c 2- | ./lychee -
